title: Inventures
tagline: Impact Venture Capital Funds
email: inventures@mymicroinvest.com
description: >
  Inventures is the first European crowd-venturing impact fund,
  a venture capital firm based in Brussels, Belgium, investing
  in early stage impact businesses.
baseurl: ''
url: 'https://www.inventures.fund'
twitter: '@inventuresfund'

gems:
exclude:
  - Gemfile
  - Gemfile.lock
