title: Inventures
tagline: Impact Venture Capital Funds
email: inventures@mymicroinvest.com
description: >
  Inventures is the first European crowd-venturing impact fund,
  a venture capital firm based in Brussels, Belgium, investing
  in early stage impact businesses.
baseurl: ''
url: 'http://inventures.fund'
phone: '+32 2 318 47 12'
twitter: '@inventuresfund'
permalink: pretty

gems:
exclude:
  - Gemfile
  - Gemfile.lock
