title: Inventures
tagline: Impact Venture Capital Funds
email: info@inventures.fund
description: >
  Inventures is the first European crowd-venturing impact fund,
  a venture capital firm based in Brussels, Belgium, investing
  in early stage impact businesses.
baseurl: ''
url: 'http://inventures.fund'
phone: '+32 472 34 14 32'
twitter: '@inventuresfund'
permalink: pretty

gems:
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
